[package]
name = "datafusion-substrait"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = "7.0"
substrait = { git = "https://github.com/andygrove/substrait", branch = "rust-bindings"}
tokio = "1.17"
async-recursion = "1.0"
