[package]
name = "datafusion-substrait"
version = "0.1.0"
edition = "2021"

[dependencies]
datafusion = { path="../../apache/arrow-datafusion/datafusion/core" }
substrait = "0.2"
tokio = "1.17"
async-recursion = "1.0"
